(define (problem Ejercicio1-1)
	(:domain Ejercicio1)
	(:objects
		princesa - Princesa
		principe - Principe
		bruja - Bruja
		profesor - Profesor
		diCaprio - DiCaprio
		oscar - Oscar
		manzana - Manzana
		rosa - Rosa
		algoritmo - Algoritmo
		oro - Oro
		Agente - Player
		z1 z2 z3 z4 z5 z6 z7 z8 z9 z10 z11 z12 z13 z14 z15 z16 z17 z18 z19 z20 z21 z22 z23 z24 z25 - Zona
		Norte Sur Este Oeste - Orientacion
	)
	(:init
		(Conexion z1 z2 Este)
		(Conexion z2 z1 Oeste)
		(Conexion z2 z3 Este)
		(Conexion z3 z2 Oeste)
		(Conexion z3 z4 Este)
		(Conexion z4 z3 Oeste)
		(Conexion z4 z5 Este)
		(Conexion z5 z4 Oeste)
		(Conexion z5 z6 Este)
		(Conexion z6 z5 Oeste)
		(Conexion z2 z7 Norte)
		(Conexion z7 z2 Sur)
		(Conexion z7 z8 Este)
		(Conexion z8 z7 Oeste)
		(Conexion z3 z8 Norte)
		(Conexion z8 z3 Sur)
		(Conexion z3 z14 Sur)
		(Conexion z14 z3 Norte)
		(Conexion z4 z15 Sur)
		(Conexion z15 z4 Norte)
		(Conexion z5 z11 Norte)
		(Conexion z11 z5 Sur)
		(Conexion z6 z25 Norte)
		(Conexion z25 z6 Sur)
		(Conexion z15 z23 Este)
		(Conexion z23 z15 Oeste)
		(Conexion z23 z24 Este)
		(Conexion z24 z23 Oeste)
		(Conexion z6 z24 Sur)
		(Conexion z24 z6 Norte)
		(Conexion z7 z13 Norte)
		(Conexion z13 z7 Sur)
		(Conexion z8 z9 Norte)
		(Conexion z9 z8 Sur)
		(Conexion z13 z9 Este)
		(Conexion z9 z13 Oeste)
		(Conexion z9 z10 Este)
		(Conexion z10 z9 Oeste)
		(Conexion z10 z16 Este)
		(Conexion z16 z10 Oeste)
		(Conexion z19 z20 Este)
		(Conexion z20 z19 Oeste)
		(Conexion z20 z21 Este)
		(Conexion z21 z20 Oeste)
		(Conexion z13 z17 Norte)
		(Conexion z17 z13 Sur)
		(Conexion z9 z18 Norte)
		(Conexion z18 z9 Sur)
		(Conexion z18 z19 Norte)
		(Conexion z19 z18 Sur)
		(Conexion z10 z12 Norte)
		(Conexion z12 z10 Sur)
		(Conexion z16 z22 Norte)
		(Conexion z22 z16 Sur)
		(Conexion z22 z21 Norte)
		(Conexion z21 z22 Sur)
		(PosicionObjeto oscar z2)
		(PosicionObjeto manzana z8)
		(PosicionObjeto rosa z18)
		(PosicionObjeto algoritmo z15)
		(PosicionObjeto oro z22)
		(PosicionPersonaje princesa z21)
		(PosicionPersonaje principe z16)
		(PosicionPersonaje bruja z12)
		(PosicionPersonaje profesor z11)
		(PosicionPersonaje diCaprio z17)
		(PosicionJugador Agente z1)
		(OrientacionJugador Norte)
		(ManoLibre)
	)
	(:goal
		(and (TieneObjeto diCaprio) (TieneObjeto princesa) (TieneObjeto bruja) (TieneObjeto profesor) (TieneObjeto principe))
	)
)
